export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const DELETE_BOOK_OPTIMISTIC = 'DELETE_BOOK_OPTIMISTIC';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const FILTER_BOOKS_BY_CATEGORY = 'FILTER_BOOKS_BY_CATEGORY';
export const FILTER_BOOKS_BY_AUTHOR = 'FILTER_BOOKS_BY_AUTHOR';
export const FILTER_BOOKS_BY_EDITORIAL = 'FILTER_BOOKS_BY_EDITORIAL';
export const FILTER_BOOKS_BY_VALUE = 'FILTER_BOOKS_BY_VALUE';
export const FILTER_BOOKS_NO_VALUE = 'FILTER_BOOKS_NO_VALUE';
export const RESET_BOOKS_FILTERS = 'RESET_BOOKS_FILTERS';

export const ORDER_BOOKS_BY_TITLE_ASC = 'ORDER_BOOKS_BY_TITLE_ASC';
export const ORDER_BOOKS_BY_TITLE_DESC = 'ORDER_BOOKS_BY_TITLE_DESC';
export const ORDER_BOOKS_BY_AUTHOR_ASC = 'ORDER_BOOKS_BY_AUTHOR_ASC';
export const ORDER_BOOKS_BY_AUTHOR_DESC = 'ORDER_BOOKS_BY_AUTHOR_DESC';
export const ORDER_BOOKS_BY_CATEGORY_ASC = 'ORDER_BOOKS_BY_CATEGORY_ASC';
export const ORDER_BOOKS_BY_CATEGORY_DESC = 'ORDER_BOOKS_BY_CATEGORY_DESC';
